translate_task:
  description: 
    Translate {sentence} from English to Korean without making mistakes.
  expected_output:
    A well formatted translation from English to korean
  agent: translator_agent

count_task:
  description: 
    Count the amount of letters in a sentence.
  expected_output:
    The number of letters in a sentence.
  agent: counter_agent